'use client'

import rab from '@/lib/rab-data.json'
import { Badge, Card, Money, PageHeader } from '@/components/app-shell'

const Button=({children}:{children:React.ReactNode})=><button className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-700">{children}</button>
export function CampaignsPage(){return <><PageHeader title="Campaign" description="Plan, target, kanal, PIC, dan progres campaign." action={<Button>Tambah campaign</Button>}/><Card><div className="flex flex-col gap-5 md:flex-row md:items-center"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-emerald-50 text-2xl">M</div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">MISVIT Pra-Akselerasi 2026</h2><Badge tone="green">Aktif</Badge></div><p className="mt-1 text-sm text-slate-500">Scale-up produksi, pemasaran, branding, promosi, legalitas, dan pengembangan SDM.</p><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-full w-[18%] rounded-full bg-emerald-500"/></div><p className="mt-1 text-xs text-slate-500">18% tahapan selesai</p></div><div className="grid grid-cols-2 gap-5 text-sm"><div><p className="text-slate-500">PIC</p><b>Irwan Helmi</b></div><div><p className="text-slate-500">Status</p><b>Perencanaan</b></div></div></div></Card></>}
export function TasksPage(){const tasks=[['Finalisasi RAB program','Irwan Helmi','review','Tinggi'],['Setup campaign marketplace','Rian','in_progress','Tinggi'],['Persiapan sertifikasi halal','Erina Delafira','in_progress','Mendesak'],['Brief konten influencer','Rian','planned','Sedang'],['Validasi vendor maklon phase 1','Erina Delafira','planned','Tinggi'],['Susun training reseller','Rian','backlog','Sedang']];return <><PageHeader title="Task tim" description="Checklist pekerjaan, PIC, prioritas, dan status review." action={<Button>Tambah task</Button>}/><Card className="overflow-x-auto p-0"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Task','PIC','Status','Prioritas','Deadline'].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{tasks.map((t,i)=><tr key={t[0]} className="border-b last:border-0"><td className="px-5 py-4 font-medium">{t[0]}</td><td className="px-5 py-4 text-slate-600">{t[1]}</td><td className="px-5 py-4"><Badge tone={t[2]==='review'?'amber':t[2]==='in_progress'?'blue':'slate'}>{t[2]}</Badge></td><td className="px-5 py-4">{t[3]}</td><td className="px-5 py-4 text-slate-500">{i<2?'7 Okt 2026':'14 Okt 2026'}</td></tr>)}</tbody></table></Card></>}
export function BudgetPage(){const cats=rab.filter(x=>x.category!=='Rekapitulasi');const total=cats.reduce((n,x)=>n+x.total,0);return <><PageHeader title="RAB & budget" description="Acuan: Template RAB Pra-Akselerasi Startup MISVIT 100%." action={<Button>Tambah item</Button>}/><div className="mb-5 grid gap-4 sm:grid-cols-3"><Card><p className="text-sm text-slate-500">Total item terisi</p><p className="mt-2 text-2xl font-bold"><Money value={total}/></p></Card><Card><p className="text-sm text-slate-500">Realisasi</p><p className="mt-2 text-2xl font-bold"><Money value={0}/></p></Card><Card><p className="text-sm text-slate-500">Sisa</p><p className="mt-2 text-2xl font-bold text-emerald-700"><Money value={total}/></p></Card></div><div className="space-y-4">{cats.map(c=><Card key={c.category}><div className="mb-4 flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold capitalize">{c.category.replace(/^\d+\.\s*/,'')}</h2><p className="text-xs text-slate-500">{c.items.length} item terisi</p></div><b><Money value={c.total}/></b></div>{c.items.length?<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><tbody>{c.items.map(i=><tr key={`${c.category}-${i.no}`} className="border-t"><td className="py-3 pr-4">{i.item}</td><td className="px-3 text-slate-500">{String(i.volume??'-')} {i.unit}</td><td className="px-3 text-right"><Money value={Number(i.unitPrice)||0}/></td><td className="pl-3 text-right font-semibold"><Money value={Number(i.amount)||0}/></td></tr>)}</tbody></table></div>:<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Belum ada item anggaran.</p>}</Card>)}</div></>}
export function ExpensesPage(){return <><PageHeader title="Pengeluaran" description="Upload bukti, review, dan approval pertanggungjawaban budget." action={<Button>Ajukan pengeluaran</Button>}/><Card><div className="py-14 text-center"><p className="font-semibold">Belum ada pengeluaran</p><p className="mt-1 text-sm text-slate-500">Ajukan expense pertama dan lampirkan nota atau invoice.</p></div></Card></>}
export function IssuesPage(){return <><PageHeader title="Issue reporting" description="Catat blocker, dampak, PIC penyelesaian, dan resolution note." action={<Button>Laporkan issue</Button>}/><Card><div className="py-14 text-center"><p className="font-semibold">Tidak ada issue terbuka</p><p className="mt-1 text-sm text-slate-500">Tim bebas blocker. Issue baru akan terlihat di sini.</p></div></Card></>}
export function ReportsPage(){return <><PageHeader title="Laporan" description="Ringkasan progres campaign dan pertanggungjawaban anggaran."/><div className="grid gap-4 md:grid-cols-3"><Card><p className="text-sm text-slate-500">Completion rate</p><p className="mt-2 text-3xl font-bold">18%</p></Card><Card><p className="text-sm text-slate-500">Budget utilization</p><p className="mt-2 text-3xl font-bold">0%</p></Card><Card><p className="text-sm text-slate-500">Open issues</p><p className="mt-2 text-3xl font-bold">0</p></Card></div></>}

