'use client'

import { useMemo, useState } from 'react'
import type { InsightResponse } from '@/lib/ai-schema'
import decks from '@/lib/deck-knowledge.json'
import { Badge, Card, PageHeader } from '@/components/app-shell'

const Button=({children,secondary=false,onClick}:{children:React.ReactNode;secondary?:boolean;onClick?:()=>void})=><button onClick={onClick} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${secondary?'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50':'bg-emerald-600 text-white hover:bg-emerald-700'}`}>{children}</button>

export function KnowledgePage(){const [selected,setSelected]=useState(0);const doc=decks[selected];const guide=[['Positioning','Feminine wash herbal Nusantara untuk muslimah aktif: bersih, segar, nyaman, dan sesuai thaharah.'],['Klaim aman','Gunakan untuk area kewanitaan luar; fokus membersihkan, kesegaran, kenyamanan, pH, dan penggunaan harian.'],['Guardrail','Jangan klaim sudah halal sebelum sertifikat terbit. Hindari klaim mengatasi keputihan, infeksi, atau mengencangkan vagina.'],['Channel','Instagram, TikTok Shop, Shopee, komunitas muslimah, apotek, klinik, toko muslimah, reseller.']];return <><PageHeader title="Campaign knowledge" description="Deck MISVIT menjadi arahan bersama untuk campaign, konten, sales, dan marketplace."/><div className="grid gap-5 xl:grid-cols-[340px_1fr]"><Card><h2 className="mb-3 font-semibold">Dokumen aktif</h2><div className="space-y-2">{decks.map((d,i)=><button key={d.file} onClick={()=>setSelected(i)} className={`w-full rounded-xl p-3 text-left text-sm ${i===selected?'bg-emerald-50 text-emerald-800':'hover:bg-slate-50'}`}><b className="block">{d.title}</b><span className="text-xs text-slate-500">{d.slides.length} slides</span></button>)}</div></Card><div className="space-y-5"><Card><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge tone="green">PPTX extracted</Badge><h2 className="mt-3 text-xl font-bold">{doc.title}</h2><p className="text-sm text-slate-500">{doc.file}</p></div><Button secondary>Hubungkan ke campaign</Button></div><div className="mt-5 grid gap-3 md:grid-cols-2">{doc.slides.slice(0,6).map(s=><div key={s.slide} className="rounded-xl bg-slate-50 p-4"><b className="text-xs text-emerald-700">SLIDE {s.slide}</b><p className="mt-2 line-clamp-4 text-sm text-slate-600">{s.text}</p></div>)}</div></Card><Card><h2 className="font-semibold">Brand & compliance guide</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{guide.map(([a,b])=><div key={a} className="rounded-xl border p-4"><b className="text-sm">{a}</b><p className="mt-1 text-sm text-slate-600">{b}</p></div>)}</div></Card></div></div></>}

export function IntegrationsPage(){const [file,setFile]=useState<File|null>(null);const [columns,setColumns]=useState<string[]>([]);async function inspect(f:File){setFile(f);const first=(await f.text()).split(/\r?\n/)[0]??'';setColumns(first.split(/[,;\t]/).map(x=>x.trim().replace(/^"|"$/g,'')));}return <><PageHeader title="Integrasi Pancake CRM" description="MVP memakai CSV export. API/webhook live diaktifkan setelah kontrak Pancake terverifikasi."/><div className="grid gap-5 xl:grid-cols-2"><Card><Badge tone="amber">CSV bridge</Badge><h2 className="mt-3 font-semibold">Import percakapan, lead, atau order</h2><p className="mt-1 text-sm text-slate-500">Data dianalisis lokal di browser pada tahap mapping. Upload database diaktifkan setelah migration.</p><label className="mt-5 block cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-10 text-center hover:border-emerald-400"><input type="file" accept=".csv,text/csv" className="hidden" onChange={e=>e.target.files?.[0]&&inspect(e.target.files[0])}/><b>{file?.name??'Pilih file CSV export Pancake'}</b><p className="mt-1 text-xs text-slate-500">CSV saja. Jangan unggah credential atau token.</p></label>{columns.length>0&&<div className="mt-4"><p className="text-sm font-semibold">Kolom terdeteksi</p><div className="mt-2 flex flex-wrap gap-2">{columns.map(c=><Badge key={c}>{c||'(kosong)'}</Badge>)}</div><div className="mt-4"><Button>Import dan analisis</Button></div></div>}</Card><Card><Badge tone="slate">Live integration</Badge><h2 className="mt-3 font-semibold">API / webhook</h2><p className="mt-1 text-sm text-slate-500">Belum diaktifkan. Perlu dokumentasi API akun Pancake, event tersedia, rate limit, dan metode autentikasi.</p><div className="mt-5 space-y-3 text-sm">{['Credential tersimpan server-side','Webhook diverifikasi signature','Event memakai idempotency key','PII diminimalkan dan akses diaudit','AI hanya memberi rekomendasi'].map(x=><div key={x} className="rounded-xl bg-slate-50 p-3">✓ {x}</div>)}</div></Card></div></>}

export function InsightsPage(){
  const fallback=useMemo(()=>[['FAQ halal muncul berulang','Buat jawaban standar: BPOM tersedia, sertifikasi halal sedang diproses.','high','67/159 chat'],['CTA edukasi perlu diuji','Bandingkan CTA edukasi keamanan/kandungan melawan CTA diskon selama 14 hari.','medium','Butuh data CTA']],[])
  const [result,setResult]=useState<InsightResponse|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('')
  async function analyze(){setLoading(true);setError('');try{const r=await fetch('/api/ai/insights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:'campaign_review',context:'Analisis campaign MISVIT berdasarkan positioning herbal Nusantara, muslimah aktif, marketplace, reseller, RAB, dan guardrail klaim. Fokus CTA, funnel, risiko, dan task PIC.'})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Analisis gagal');setResult(body)}catch(e){setError(e instanceof Error?e.message:'Analisis gagal')}finally{setLoading(false)}}
  const list=result?.insights.map(x=>[x.title,x.recommendation,x.priority,x.evidence])??fallback
  return <><PageHeader title="AI marketing insights" description="9router model mid-task. Rekomendasi berbasis bukti; manager wajib approve sebelum menjadi task." action={<Button onClick={analyze}>{loading?'Menganalisis…':'Jalankan analisis'}</Button>}/>{error&&<p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{result&&<Card className="mb-4"><Badge tone="green">mid-task</Badge><p className="mt-3 text-sm text-slate-600">{result.summary}</p></Card>}<div className="space-y-4">{list.map(([title,rec,p,e])=><Card key={title}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex gap-2"><Badge tone={p==='high'||p==='urgent'?'red':'amber'}>{p}</Badge><Badge tone="blue">Draft insight</Badge></div><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-600">{rec}</p><p className="mt-3 text-xs font-medium text-slate-500">Evidence: {e}</p></div><div className="flex shrink-0 items-start gap-2"><Button secondary>Tolak</Button><Button>Approve → Task</Button></div></div></Card>)}</div></>
}
